T = {
0:"SLP — Sound Light Prod | Show, Concert and Sound & Lighting Producer in France & Europe",
1:"SLP - Sound Light Prod: producer and organiser of shows and concerts, sound and lighting services, artist booking and touring across France and Europe.",
3:"Home",4:"Our Artists",5:"Technical services",6:"How we work",7:"Events",8:"Gallery",9:"Contact",10:"Equipment sales (FR)",
11:"Sound · Lighting · Booking · Touring",
12:"We produce",13:"events people remember",
14:"SLP provides sound, lighting and production for your public and private events — and brings on stage the artists who make them come alive. We work across France and Europe. One point of contact, one team, zero compromise.",
15:"Request a quote →",16:"Our roster",17:"Artists ready",18:"to set your stage on fire",19:"See all artists →",20:"Previous artist",
22:"Pop / Rock",23:"High-energy pop/rock covers with real on-stage chemistry.",25:"Pop-Rock Electro Duo",26:"A supercharged duo reworking pop-rock covers with an electro twist.",
28:"Funk / Soul",29:"Horns, groove and rhythm'n'blues for a non-stop dancefloor.",31:"Pop / Rock / Funk",32:"A versatile duo, from pop classics to the most danceable funk.",
34:"Cabaret",35:"A touring cabaret revue: feathers, rhinestones and French cancan.",37:"A live four-piece tribute to Calogero, 2 hours of concert.",38:"Next artist",
39:"years of field experience",40:"point of contact, from quote to stage",41:"What we do",42:"Two trades,",43:"one standard",
44:"Technical services",45:"Sound, stage lighting and technical management tailored to your venue, your audience and your budget.",46:"Discover →",
47:"Programming & shows",48:"Turnkey programming: artists selected from our network, contracts handled and everything coordinated right up to the stage.",
49:"SLP event — audience and concert lighting",50:"Have a project in mind?",51:"Let's talk about your",52:"next event",53:"Free, no-obligation quote, fast reply.",
56:"Sound, lighting, booking and event production in France and Europe.",58:"Follow us",63:"Legal notice",64:"Shop T&Cs (FR)",
65:"Our Artists & Live Bands — Alchimie, Cache Candy, The Fine Allies... | SLP",
66:"Discover our live bands touring across France and Europe: Alchimie, Cache Candy, The Fine Allies, NooN Coverband, Panache, Voice of Freedom — Cabaret, Pop Rock, Jazz Soul Funk, French Pop.",
67:"Our catalogue",68:"Our artists",69:"SLP selects and represents artists by type of show. Choose a category to discover the matching artist.",
70:"Cache Candy logo",71:"A pop-rock electro duo formed in 2008, blending nostalgic ballads with energetic, crowd-pleasing tracks. Over 300 concerts across France, from Printemps de Bourges to Garorock — currently our biggest production.",
72:"SLP exclusive",73:"Festivals",74:"Concerts",75:"Public events",76:"Discover Cache Candy",77:"Discover",78:"Browse by type of show",79:"Cabaret Show",80:"Type of show",
81:"Cover bands",83:"French Pop",86:"Want to book an artist?",87:"We'll suggest the right package for your budget and atmosphere.",
88:"Sound & Lighting for Concerts and Shows — France & Europe | SLP",
89:"Sound and lighting services for your concerts and shows: PA, stage lighting, technical management. We work across France and Europe.",
90:"Sound and lighting designed for your venue, your audience and the atmosphere you want to create — set up and run by us, from the first line check to the last encore. Indoor or outdoor concerts, shows, conventions, weddings, community events: we adapt our setup to every event format.",
91:"What we do",92:"Full technical production, from A to Z",93:"Sound",
94:"Front-of-house PA, stage monitors and a digital console mixed live, matched to the audience size and the venue's acoustics.",
95:"Stage lighting",96:"Moving heads, washes, haze effects and a DMX control desk for an atmosphere that follows the rhythm of your event.",
97:"Structure & rigging",98:"Truss, stands and safe lifting to support lighting and speakers by the book.",
99:"Pyrotechnics",100:"Fireworks displays and custom stage effects, carried out safely with all the required permits.",
101:"Technical crew",102:"A technician on site on the day to run sound and lighting live, from soundcheck to load-out.",
103:"Advice & planning",104:"A technical site visit and a stage plot tailored to your venue, well before the day of the event.",
105:"Every event format",106:"A setup that adapts, whatever the event",
107:"Bands, solo artists or festivals, indoors or outdoors: sound and lighting calibrated for the stage and the venue.",
108:"Shows & theatre",109:"Companies, troupes and performances: discreet, precise operation in service of the staging.",
110:"Conventions & seminars",111:"Room PA, wireless microphones and stage lighting for your speeches and key business moments.",
112:"Weddings & receptions",113:"Tailor-made sound and lighting atmosphere, from the ceremony to the dance party.",
114:"Community festivals & public events",115:"Fairs, village fêtes, galas: a reliable setup designed around the budget and constraints of community organisations.",
116:"Corporate evenings & launches",117:"Product launches, open days, company events: a professional image, from sound to lighting.",
118:"An event that needs sound?",119:"Request your",120:"technical quote",121:"Site visit available before quoting for large audiences.",
122:"How We Work — Show Producer & Organiser | SLP Sound Light Prod",
123:"How we work at SLP, show producer and organiser: client and audience satisfaction first, with artists supported from contract to stage so they can focus on the music.",
124:"Programming & touring",125:"SLP selects and represents the artists in its network for your events. One single point of contact, from contract to stage — we coordinate the artist's appearance from start to finish.",
126:"What drives us",127:"Satisfaction, above all",
128:"Our goal is simple: the satisfaction of our clients and of the audience. It guides every choice we make, from selecting the artists to technical coordination on the day.",
129:"We support artists at every step so they only have one thing to think about: the music.",
130:"Our positioning",131:"A show distributor, not just a middleman",
132:"As a show distributor, SLP doesn't just pass on a contact: we select the best-suited artist from our network, handle the contracts and coordinate all the logistics, right through to the technical delivery on stage.",
133:"You have one single point of contact, from choosing the artist to the last note on stage.",
134:"What we offer",135:"Two ways to work with us",136:"Artist booking",
137:"Looking for a band or a DJ for your event? We'll suggest a selection of artists from our network, suited to your atmosphere and budget, with all the logistics taken care of.",
138:"Tailor-made events",139:"Concert, themed night, bespoke show: we design the event from A to Z, from artistic selection to technical delivery on stage.",
140:"Cabaret show represented by SLP — artists and dancers in feathered costumes on stage",
141:"How it works",142:"From idea to stage",143:"You get in touch",144:"Describe your event, the atmosphere you're after and your budget.",
145:"Selection & quote",146:"We suggest one or more suitable artists, with a clear quote and no surprises.",
147:"Contracts",148:"SLP contracts the performance with the artist and handles all the paperwork.",
149:"On-the-day coordination",150:"Logistical, technical and artistic coordination for a flawless event.",
151:"One contract, one invoice, one point of contact",152:"A network of local and regional artists",153:"Can be combined with our sound/lighting services",154:"Public and private events, any audience size",
155:"Programming to plan?",156:"next show",157:"Tell us about your event, we'll take care of the rest.",
158:"Concert Dates — Alchimie, Cache Candy & Our Artists | SLP Sound Light Prod",
159:"All upcoming concerts and dates for our artists (Alchimie, Cache Candy, The Fine Allies, NooN Coverband, Panache, Voice of Freedom), across France.",
160:"All our upcoming concerts",161:"Find the next dates of our artists here — concerts, festivals and events open to the public.",162:"Loading events…",
163:"Gallery — SLP Sound Light Prod",164:"Photos of our work: events with sound, lighting and production by SLP.",165:"Our work",166:"A glimpse of our sound, lighting and artist booking work.",
167:"On video",168:"Our artists on video",176:"The Fine Allies — Live excerpt",177:"Live excerpt",178:"NooN Coverband — Performance excerpt",179:"Performance excerpt",
180:"Alchimie — Pop Rock covers teaser",181:"Pop Rock covers teaser",182:"Fancy working together?",183:"Free, no-obligation quote.",
184:"Contact — Sound, Lighting & Booking Quotes | SLP Sound Light Prod",185:"Contact SLP for a sound, lighting, booking or artist quote — anywhere in France and Europe.",
186:"Let's talk about your project",187:"Sound, lighting, booking or artists: we'll get back to you quickly.",188:"Contact details",189:"Email",190:"Phone",191:"Address",194:"Area covered",195:"France / Europe",
196:"Write to us",197:"The form opens your email app with the message pre-filled, ready to send.",198:"Name",199:"Subject",200:"Technical services quote",201:"Other request",202:"Event date",203:"e.g. 15 September 2026",205:"Send message",206:"You can also write directly to contact@soundlightprod.fr",
207:"Cabaret Show — Our Artists — SLP Sound Light Prod",208:"Cabaret show represented by SLP: Panache, a touring cabaret revue with feathers, rhinestones and costumed acts.",209:"← Our Artists",
210:"Feathered revues, costumed acts and flamboyant staging — for your galas and prestige evenings.",211:"Cabaret Revue",
212:"A touring cabaret revue combining dynamic tableaux, live singing, feathers and rhinestones — to light up your galas, corporate evenings and private events.",
213:"Galas & prestige evenings",214:"Works councils",215:"Private events",216:"Discover Panache",
217:"DJ — Our Artists — SLP Sound Light Prod",218:"DJs represented by SLP: tailor-made sets for private parties, weddings and corporate events.",
219:"Tailor-made sets from cocktail hour to the dancefloor, for your private parties, weddings and corporate events.",220:"Our DJs are coming to this section very soon",
221:"We're putting together a selection of DJs for your private parties, weddings and corporate events. Check back soon, or contact us now to talk it through.",
222:"Cover Bands — Our Artists — SLP Sound Light Prod",223:"Cover bands represented by SLP: Alchimie and NooNCoverBand, to liven up your private parties, weddings and events.",
224:"Varied cover repertoires, on-stage chemistry and band energy, to liven up private parties, weddings and festive events.",
225:"A pop/rock band formed in 2018. Covers of the great standards, driven by on-stage chemistry and the joy of sharing music.",
226:"Private parties",227:"Corporate events",228:"Food markets",229:"Discover Alchimie",
231:"A vocals/bass duo spanning international hits, French chanson and disco/funk classics. Nearly 120 concerts at campsites, bars, country markets and private parties.",
232:"Weddings",233:"Campsites",234:"Discover NooNCoverBand",
235:"Jazz Soul Funk — Our Artists — SLP Sound Light Prod",236:"Jazz Soul Funk represented by SLP: The Fine Allies, seven musicians and a singer for a show full of groove.",
237:"Groove, horns and soulful vocals for a warm atmosphere, from cocktail dinner to concert stage.",
239:"Seven musicians and a singer joining forces for a lively, warm show full of groove — from James Brown to Jamiroquai.",240:"Corporate evenings",241:"Discover The Fine Allies",
242:"French Pop — Our Artists — SLP Sound Light Prod",243:"French pop represented by SLP: Cache Candy, a pop-rock electro duo blending nostalgic ballads with energetic tracks.",
244:"Pop-rock electro and crowd-uniting energy, between nostalgia and tracks that make you want to dance.",245:"Pop-Rock Electro",
246:"A pop-rock electro duo formed in 2008: Bruno-Bastien on vocals and Loïc on drums, blending nostalgic ballads with energetic, crowd-pleasing tracks. Over 300 concerts across France, from Printemps de Bourges to Garorock.",
247:"Tributes — Our Artists — SLP Sound Light Prod",248:"Tribute shows represented by SLP: stage tributes to the greatest voices, for your parties and events.",
249:"Stage tributes to the greatest voices, performed by passionate artists — for evenings where emotion takes over.",
250:"A live four-piece tribute to Calogero, to relive \"En apesanteur\", \"Voler de nuit\" or \"Yalla\" in a 2-hour concert format.",
251:"Live band",252:"Four-piece",253:"Discover Tribute Calogero",
255:"Alchimie, a pop/rock band formed in 2018, represented by SLP for your events across France and Europe.",256:"← Cover bands",
257:"A pop/rock band driven by on-stage chemistry and the joy of sharing music.",258:"News",259:"What's new",
260:"Alchimie is a pop/rock band formed in 2018 by former members of the band Antidote.",
261:"The band offers a selection of pop rock covers — sung in French, English and Spanish — along with a few original songs, to liven up private parties, weddings, seminars, concerts and corporate events.",
262:"Alchimie performs with its own PA system, in formats that suit bars and large venues alike.",
263:"Line-up",264:"On stage",266:"Vocals, guitar",268:"Lead guitar",270:"Bass",272:"Drums",273:"Line-up given for information only — may vary depending on the date.",
274:"Alchimie in concert, acoustic performance",275:"Alchimie in concert, full band on stage",276:"Alchimie in concert outdoors",277:"See the band in action",279:"Formed in 2018",
280:"Available across France",281:"Multilingual covers + originals",282:"Find the band",283:"Online",284:"Official website ↗",
286:"Want to book them?",287:"Book Alchimie",288:"for your event",289:"SLP represents this artist and coordinates all the logistics of your event.",
291:"Cache Candy, a pop-rock electro duo represented by SLP for your events.",292:"← French Pop",
293:"A duo formed in 2008, between nostalgic ballads and electro-pop energy — over 300 concerts across France.",
294:"Cache Candy is a pop-rock electro duo formed in 2008. Spotted by a record label and a distributor, the project has released several EPs and an album, and played over 300 concerts in France.",
295:"The band has built an \"Electro Pop Love\" universe, between nostalgic ballads and energetic, crowd-pleasing tracks, all written, composed and produced in-house with a demanding DIY approach. Its journey has taken it all the way to the beaches of the Mediterranean, in front of more than 20,000 people.",
296:"In 2017, Cache Candy was voted \"best band in the Greater South-West\" and came second in a contest run by NRJ12 among more than 800 entrants.",
297:"Now led by Bruno-Bastien and Loïc, the band carries on as a duo where vocals, drums and instruments swap hands throughout the live show — and is preparing its new album,",
299:"Cache Candy — visual identity of the album HAPPY END",300:"A duo on stage",302:"Vocals",304:"5.9K Facebook followers",305:"1.6K Instagram followers",306:"30 to 40 live shows a year",
307:"Where they've played",308:"A few of the band's stages",314:"In pictures",315:"Cache Candy in concert",316:"Cache Candy in concert, audience",317:"Cache Candy acoustic concert",318:"Listen",319:"Cache Candy on Spotify",
321:"📄 Press kit (PDF, French) ↓",322:"Formed in 2008",323:"300+ concerts in France",324:"Book Cache Candy",
326:"A live tribute band honouring Calogero, represented by SLP for your festivals, corporate parties and concerts.",327:"← Tributes",
328:"The tribute to Calogero — a live four-piece revisiting the greatest songs of his repertoire, for an evening of sharing and nostalgia.",
329:"A red star, a mirror pickguard, an upside-down neck... Every Calogero fan will recognise this instrument. Nicolas, one of his devoted admirers, took on the challenge of customising it himself: in 2024 this tribute was born out of a love at first sight on stage back in 2007 — the night that made Nicolas decide to turn music into his career.",
330:"Backed by three talented musicians, the band revisits the greatest standards of Calogero's repertoire, drawing on the four-piece format of the \"Les Feux d'Artifice Tour\" (2014) and \"Liberté Chérie Tour\" (2018). A major figure of French popular music, his songs speak to a wide audience: \"Yalla\", \"Je joue de la musique\", \"En apesanteur\", \"Voler de nuit\", \"C'est dit\"...",
331:"Wherever you're from and whatever your age: come aboard for a 2-hour concert with Tribute Calogero and let the magic happen.",
332:"The concert lasts 2 hours, fully live, with sound, lighting and staging handled by SLP depending on the package chosen. An evening of nostalgia and good vibes, for young and old alike!",
333:"The band",334:"The four-piece",336:"Bass — founder",
337:"Deeply moved by a Calogero concert at the Zénith in Toulouse in 2007, he made it his calling. A professional for 12 years and a singer-songwriter, he released an album in 2018.",
339:"Guitar",340:"A lover of live music (over 200 concerts attended), passionate about guitar and analogue sound. A professional musician for 25 years.",
342:"Keyboards",343:"Trained on piano from the age of 15, steeped in progressive rock and jazz, bringing creativity to the sound and the style.",
345:"A graduate of the Musique Académie Internationale in Nancy (2009), with a straight, effective playing style in service of the tribute.",
347:"Watch",348:"The teasers",351:"Live four-piece — bass, guitar, keyboards, drums",352:"2 hours of live concert",353:"Four-piece format inspired by Calogero's tours (2014, 2018)",354:"Professional musicians, decades of stage experience",
355:"Tribute to Calogero",356:"Live band — four-piece",357:"Ideal for festivals, concerts, corporate parties",358:"Book",
359:"DJ Provisoire — SLP Sound Light Prod",360:"DJ Provisoire, tailor-made sets represented by SLP for your events.",361:"Sound & Lighting",364:"★ Only at SLP",365:"Logo coming soon",
366:"DJ Provisoire offers sets designed to carry the whole evening: a gentle cocktail-hour vibe, then a gradual build in energy all the way to the dancefloor.",
367:"A pop, house and disco-funk repertoire that adapts to any atmosphere — from an intimate reception to a full-on dance party.",
368:"One DJ, a tailor-made evening",369:"DJ set, club atmosphere",370:"Videos",371:"A few excerpts",372:"Video coming soon",373:"Solo DJ",374:"Available anywhere in France",376:"Flexible sets, from cocktail hour to the dancefloor",377:"Want to book him?",378:"Book DJ Provisoire",
379:"SLP · Sound Light Prod · 173 rue de Courcelles, 75017 Paris · SIRET 130 415 045 00017 — © 2026 ·",
381:"NooNCoverBand, a pop/rock/funk duo available anywhere in France, represented by SLP for your events.",383:"A duo available anywhere in France, for evenings as intimate as they are danceable.",
385:"NooNCoverBand was born three years ago when two artists met — a singer and a bass player. Drawing on varied musical backgrounds — soul, reggae, afro and funk — they brought their worlds together to give their audiences memorable evenings.",
386:"Their repertoire, designed to fit any atmosphere, can be as intimate (reception, drinks) as it is full-on dance. Each performance, up to two and a half hours non-stop, starts gently before building up energy as the evening goes on.",
387:"Musically: plenty of international pop (Rihanna, Dua Lipa, The Weeknd, Justin Timberlake, Daft Punk), French chanson (Rita Mitsouko, Niagara, Superbus, Juliette Armanet, -M-) and 80s disco/funk classics (Chic, Patrick Hernandez, Kool & The Gang, Michael Jackson, Jamiroquai, Claudio Capéo). A living repertoire, regularly refreshed with new songs.",
388:"After nearly one hundred and twenty concerts at campsites, bars, country markets and private parties, NooNCoverBand has built a loyal audience and many partners who keep booking them again.",
389:"A duo, two complementary voices",390:"NooNCoverBand, singer and bass player portrait",391:"NooNCoverBand, bass player in concert",392:"NooNCoverBand, singer mid-performance",393:"NooNCoverBand in concert, black and white",
394:"A few live excerpts",395:"NooNCoverBand — Live excerpt",396:"Where they've performed",397:"Nearly 120 concerts to their name",398:"Bars",399:"Country markets",400:"Vocals / bass duo",402:"Sets up to 2h30 non-stop, adaptable atmosphere",404:"Book NooNCoverBand",
406:"Panache, a touring cabaret revue represented by SLP: feathers, rhinestones and French cancan for your galas, corporate evenings and private events.",407:"← Cabaret Show",408:"Casinos & campsites",409:"Panache — Feather Revue",
410:"Panache is a high-end cabaret revue, designed to travel anywhere in France. In a flexible format of 4 to 8 artists, it moves through dynamic, colourful and innovative tableaux, carried by live singing.",
411:"Feathers, rhinestones and French cancan shape the show's visual world, in the purest spirit of the Parisian music-hall revues, right up to a red-white-and-blue finale that sets the room ablaze.",
412:"Represented by SLP, the revue adapts to the length and format of your event — from a 30-minute showcase to a full 1h30 evening — and travels with its own sound and lighting crew.",
413:"The show",414:"What the revue includes",415:"4 to 8 artists",416:"Flexible format to suit your event",417:"30 min to 1h30",418:"Adjustable length",419:"Live singing",420:"Dynamic, colourful tableaux",
421:"Feathers & rhinestones",422:"French cancan, Parisian revue spirit",423:"Tricolour finale",424:"Blue, white, red",425:"Tech included",426:"Dedicated sound & lighting crew",427:"Panache — artist in stage costume",428:"The revue on tour",
429:"Your browser does not support this video.",430:"Ideal for",431:"A revue that adapts to your event",432:"Afterworks & works councils",433:"Casinos",434:"Campsites & holiday resorts",435:"Touring revue",436:"Sound & lighting crew included",
437:"Want to book Panache?",438:"Book this revue",439:"SLP represents this show and coordinates all the logistics of your event.",
441:"The Best ABBA Tribute, a live tribute band to ABBA, represented by SLP for your festivals, corporate parties and concerts.",442:"ABBA Tribute",
443:"A full live band bringing ABBA's greatest hits back to life — two outstanding singers and seasoned musicians, for an evening of nostalgia and good vibes.",444:"2 singers + musicians",
445:"In the history of pop, ABBA holds a special place. Who doesn't remember timeless hits like \"Dancing Queen\", \"Waterloo\", \"Mamma Mia\", \"Voulez-Vous\" or \"The Winner Takes It All\"? With more than 200 million albums sold (370 million records in total), ABBA remains one of the best-selling bands in music history.",
446:"The Best ABBA Tribute is led by two lead singers at the top of their game and musicians who play entirely live — a rare standard in the world of tribute acts, and one of the keys to their success. The band has performed in front of more than 15,000 spectators in Helmond (Kasteeltuinconcerten) and at the TT Assen festival, as well as abroad: Russia, Romania, Liechtenstein.",
447:"Hailed by the Dutch and international press as one of the best ABBA tributes in the world, the band promises an evening of nostalgia and good vibes, for young and old alike, with timeless hits like \"Dancing Queen\", \"Waterloo\", \"Mamma Mia\", \"Voulez-Vous\" or \"The Winner Takes It All\".",
448:"The teaser",449:"Full live band — vocals, musicians, sound engineer",450:"More than 15,000 spectators in Helmond and TT Assen",451:"Acclaimed by the Dutch and international press",452:"Tribute to ABBA",453:"Live band — 2 singers + musicians",
455:"The Fine Allies, a funk soul rhythm'n'blues band represented by SLP for your events across France and Europe.",456:"← Jazz Soul Funk",457:"Seven musicians and a singer, united by a single motto: groove.",
458:"The Fine Allies is a union of seven musicians and a singer from varied musical backgrounds, brought together by a shared desire: to play the music that moves them.",
459:"On stage, the band delivers a lively, warm show of funk, soul and rhythm'n'blues, with touches of jazz, reggae and rock — from James Brown to Jamiroquai, by way of Stevie Wonder, Amy Winehouse and Tower of Power.",
460:"The band performs regularly all over France: festivals, bars, weddings and private events.",461:"Eight artists on stage",465:"Keyboards, backing vocals",467:"Tenor saxophone",469:"Alto saxophone",471:"Trumpet",474:"Drums, backing vocals",
475:"The Fine Allies in concert, horn section",476:"The Fine Allies in concert, full band on stage",477:"The Fine Allies in concert outdoors",478:"The Fine Allies in concert, trombone solo",486:"8 musicians",487:"Festivals, weddings and private events",488:"Book The Fine Allies",
490:"Voice of Freedom, tribute shows to Etta James and Nina Simone, represented by SLP for your events.",
493:"A heartfelt tribute to the greatest voices of American soul and blues, from Etta James to Nina Simone.",
496:"Voice of Freedom is a band of five musicians with a passion for blues and soul, gathered around singer Wiennen Silveira. After the success of their Nina Simone Tribute in 2018, they came back together to pay homage to another iconic figure: Etta James.",
497:"Etta James was an artist driven by rage — against an unhappy childhood, against paternalistic America, against the men who betrayed her — a rage that carried her through drugs and anguish so that, against all odds, she could keep living and singing. Paying tribute to this great singer, little known in France, and conveying the beauty of her cry: that is the ambitious project the musicians of Voice of Freedom have set themselves.",
498:"For the length of a show, they dive into 1950s-60s Black America and follow the chaotic path of a virtuoso, tormented diva who redefined blues singing and inspired the greatest voices across the Atlantic. More than an imitation, their Tribute is a true interpretation of Etta James's work — Wiennen Silveira, backed by four talented musicians, takes the audience in her footsteps, through her failed love affairs, her boundless joys and her rage.",
499:"The band also offers a second Tribute show, dedicated to",
501:", created in 2018. Both shows have been praised on stage and on the radio, notably on France Bleu / ICI, where the band was invited on the programme « La Nouvelle Scène ».",
502:"Wiennen Silveira's journey resonates strongly with Nina Simone's. Born in India, she grew up in Qatar in a family of foreign workers, facing severe discrimination. That is where she learned the piano and joined her parish choir. Later, her studies led her to discover American blues, jazz and rock — Nina Simone and Etta James above all, two influences that left a lasting mark on her. To escape an arranged marriage, she left alone for Hyderabad, where she began singing and playing guitar in the city's bars. She then settled in the South of France, where in 2012 she founded the funk-rock trio WAT, before launching the Nina Simone project in 2018 with the musicians of Voice of Freedom.",
503:"Five artists on stage",510:"Two shows",512:"Blues diva, 1950s-60s",513:"Created in 2018",514:"Voice of Freedom on stage",515:"In the media",516:"A band on the airwaves",
519:"5 musicians",520:"Based in Châteauroux, Indre",522:"2 shows: Etta James, Nina Simone",523:"Book Voice of Freedom",
524:"Legal notice — SLP Sound Light Prod",525:"← Back to the site",526:"Site publisher",528:"SARL (limited company) with share capital of €2,500",529:"SIRET: 130 415 045 00017",530:"APE code: 9001Z",
531:"Registered office: 173 rue de Courcelles, 75017 Paris, France",532:"Email:",533:"Phone: +33 6 31 94 96 53",534:"Hosting",535:"Site hosted by Cloudflare, Inc.",536:"101 Townsend Street, San Francisco, CA 94107, United States",
537:"Intellectual property",538:"All content on this site (text, images, logos, graphics) is the property of SLP or its partners, unless otherwise stated, and may not be reproduced without prior permission.",
539:"Personal data",540:"Information collected through the forms on this site (contact, order, booking) is used solely to process your request and is never passed on to third parties for commercial purposes. Under the GDPR, you have the right to access, rectify and delete your data, which you can exercise by emailing",
541:"Cookies",542:"This site does not use advertising tracking cookies. Technical cookies may be used to ensure the shopping cart works properly.",
}
JS = {"`Nom : ${name}\\nEmail : ${email}\\nDate de l'événement : ${dateEvent}":"`Name: ${name}\\nEmail: ${email}\\nEvent date: ${dateEvent}",
      "Aucun concert public programmé pour le moment — revenez bientôt !":"No public concerts scheduled at the moment — check back soon!",
      "Agenda momentanément indisponible.":"Events temporarily unavailable."}
LOCALE="en-GB"
T.update({544:"A full live band celebrating ABBA's greatest hits.",546:"The Best ABBA Tribute logo",547:"A full live band, acclaimed by the Dutch and international press, bringing ABBA's greatest hits back to life with two outstanding singers and seasoned musicians.",548:"Corporate parties",549:"Discover The Best ABBA Tribute"})
