T = {
0:"SLP — Sound Light Prod | Productora de Espectáculos, Conciertos, Sonido e Iluminación en Francia y Europa",
1:"SLP - Sound Light Prod: productora y organizadora de espectáculos y conciertos, servicios de sonido e iluminación, contratación y distribución de artistas en toda Francia y Europa.",
3:"Inicio",4:"Nuestros artistas",5:"Servicios técnicos",6:"Cómo trabajamos",7:"Agenda",8:"Galería",9:"Contacto",10:"Venta de material (FR)",
11:"Sonido · Iluminación · Booking · Distribución",
12:"Producimos",13:"eventos que dejan huella",
14:"SLP pone el sonido, la iluminación y la producción de sus eventos públicos o privados, y sube al escenario a los artistas que les darán vida. Trabajamos en toda Francia y Europa. Un solo interlocutor, un equipo, cero concesiones.",
15:"Pedir presupuesto →",16:"Nuestro catálogo",17:"Artistas listos",18:"para encender su escenario",19:"Ver todos los artistas →",20:"Artista anterior",
22:"Pop / Rock",23:"Versiones pop/rock llenas de energía y complicidad en el escenario.",25:"Dúo Pop-Rock Electro",26:"Un dúo supervitaminado que reinventa versiones pop-rock en clave electro.",
28:"Funk / Soul",29:"Metales, groove y rhythm'n'blues para una pista de baile sin pausa.",31:"Pop / Rock / Funk",32:"Un dúo versátil, del repertorio pop al funk más bailable.",
34:"Cabaret",35:"Revista de cabaret itinerante: plumas, strass y french cancan.",37:"Cuarteto en directo en homenaje a Calogero, 2 horas de concierto.",38:"Artista siguiente",
39:"años de experiencia sobre el terreno",40:"interlocutor, del presupuesto al escenario",41:"Nuestros universos",42:"Dos oficios,",43:"una misma exigencia",
44:"Servicios técnicos",45:"Sonorización, iluminación escénica y dirección técnica adaptadas a su sala, su público y su presupuesto.",46:"Descubrir →",
47:"Programación y espectáculos",48:"Una programación llave en mano: selección de artistas de nuestra red, contratación y coordinación hasta el escenario.",
49:"Evento SLP — público y juego de luces en concierto",50:"¿Tiene un proyecto en mente?",51:"Hablemos de su",52:"próximo evento",53:"Presupuesto gratuito y sin compromiso, respuesta rápida.",
56:"Sonido, iluminación, booking y producción de eventos en Francia y Europa.",57:"Navegación",58:"Síganos",63:"Aviso legal",64:"Condiciones de venta (FR)",
65:"Nuestros artistas y grupos en directo — Alchimie, Cache Candy, The Fine Allies... | SLP",
66:"Descubra nuestros grupos en directo, que actúan en toda Francia y Europa: Alchimie, Cache Candy, The Fine Allies, NooN Coverband, Panache, Voice of Freedom — Cabaret, Pop Rock, Jazz Soul Funk, Pop francés.",
67:"Nuestro catálogo",68:"Nuestros artistas",69:"SLP selecciona y distribuye artistas por tipo de espectáculo. Elija una categoría para descubrir el artista correspondiente.",
70:"Logotipo de Cache Candy",71:"Dúo pop-rock electro nacido en 2008, entre baladas nostálgicas y temas enérgicos que unen al público. Más de 300 conciertos por toda Francia, del Printemps de Bourges a Garorock: actualmente nuestra mayor producción.",
72:"Exclusiva SLP",73:"Festivales",74:"Conciertos",75:"Eventos públicos",76:"Descubrir Cache Candy",77:"Descubrir",78:"Explorar por tipo de espectáculo",79:"Espectáculo de cabaret",80:"Tipo de espectáculo",
81:"Grupos de versiones",83:"Pop francés",86:"¿Quiere programar a un artista?",87:"Le proponemos la fórmula adecuada a su presupuesto y al ambiente que busca.",
88:"Sonido e iluminación para conciertos y espectáculos — Francia y Europa | SLP",
89:"Servicios técnicos de sonido e iluminación para sus conciertos y espectáculos: sonorización, iluminación escénica, dirección técnica. Trabajamos en toda Francia y Europa.",
90:"Un sonido y una iluminación pensados para su sala, su público y el ambiente que quiere crear, instalados y gestionados por nosotros, desde el primer ajuste hasta el último bis. Conciertos en sala o al aire libre, espectáculos, convenciones, bodas, fiestas asociativas: adaptamos nuestra técnica a cada formato de evento.",
91:"Lo que hacemos",92:"Una producción técnica completa, de principio a fin",93:"Sonorización",
94:"Sistema de PA, monitores de escenario y mesa digital mezclada en directo, adaptados al aforo y a la acústica del lugar.",
95:"Iluminación escénica",96:"Cabezas móviles, washes, efectos de humo y mesa de control DMX para un ambiente que sigue el ritmo de su evento.",
97:"Estructuras y rigging",98:"Truss, soportes y elevación segura para sostener luces y altavoces según las normas del oficio.",
99:"Pirotecnia",100:"Fuegos artificiales y efectos escénicos a medida, realizados con total seguridad y con las autorizaciones necesarias.",
101:"Técnico en directo",102:"Un técnico presente el día del evento para llevar el sonido y la luz en directo, de la prueba de sonido al desmontaje.",
103:"Asesoramiento y estudio",104:"Una visita técnica y un plano de implantación adaptados a su sala, antes incluso del día del evento.",
105:"Todo tipo de eventos",106:"Una técnica que se adapta, sea cual sea el evento",
107:"Grupos, solistas o festivales, en sala o al aire libre: sonido e iluminación calibrados para el escenario y el lugar.",
108:"Espectáculos y teatro",109:"Compañías, grupos y funciones: una técnica discreta y precisa al servicio de la puesta en escena.",
110:"Convenciones y seminarios",111:"Sonorización de sala, micrófonos inalámbricos e iluminación de escenario para sus intervenciones y momentos clave profesionales.",
112:"Bodas y recepciones",113:"Ambiente sonoro y luminoso a medida, de la ceremonia a la fiesta.",
114:"Fiestas asociativas y eventos públicos",115:"Ferias, fiestas de pueblo, galas: una técnica fiable pensada para el presupuesto y las limitaciones de las asociaciones.",
116:"Veladas corporativas e inauguraciones",117:"Lanzamientos de producto, jornadas de puertas abiertas, eventos de empresa: una imagen profesional, del sonido a la luz.",
118:"¿Un evento que sonorizar?",119:"Pida su",120:"presupuesto técnico",121:"Visita técnica posible antes del presupuesto para grandes aforos.",
122:"Cómo trabajamos — Productora y organizadora de espectáculos | SLP Sound Light Prod",
123:"Cómo trabajamos en SLP, productora y organizadora de espectáculos: la satisfacción de los clientes y del público, con artistas acompañados del contrato al escenario para que solo piensen en la música.",
124:"Programación y distribución",125:"SLP selecciona y distribuye a los artistas de su red para sus eventos. Un único interlocutor, del contrato al escenario: coordinamos la actuación del artista de principio a fin.",
126:"Lo que nos guía",127:"La satisfacción, ante todo",
128:"Nuestro objetivo es sencillo: la satisfacción de nuestros clientes y del público. Es lo que guía cada una de nuestras decisiones, desde la selección de los artistas hasta la coordinación técnica el día del evento.",
129:"Acompañamos a los artistas en cada etapa para que solo tengan que pensar en una cosa: la música.",
130:"Nuestro posicionamiento",131:"Distribuidor de espectáculos, no un simple intermediario",
132:"Como distribuidor, SLP no se limita a pasarle un contacto: seleccionamos al artista más adecuado de nuestra red, gestionamos la contratación y coordinamos toda la logística, hasta la realización técnica en el escenario.",
133:"Tiene un único interlocutor, desde la elección del artista hasta la última nota en el escenario.",
134:"Lo que ofrecemos",135:"Dos formas de trabajar con nosotros",136:"Programación de artistas",
137:"¿Busca un grupo o un DJ para su evento? Le proponemos una selección de artistas de nuestra red, adaptada a su ambiente y a su presupuesto, con toda la logística a nuestro cargo.",
138:"Eventos a medida",139:"Concierto, fiesta temática, espectáculo a medida: diseñamos el evento de principio a fin, de la selección artística a la realización técnica en el escenario.",
140:"Espectáculo de cabaret distribuido por SLP — artistas y bailarinas con trajes de plumas en el escenario",
141:"Cómo funciona",142:"De la idea al escenario",143:"Nos contacta",144:"Describa su evento, el ambiente que busca y su presupuesto.",
145:"Selección y presupuesto",146:"Le proponemos uno o varios artistas adecuados, con un presupuesto claro y sin sorpresas.",
147:"Contratación",148:"SLP contrata la actuación con el artista y se encarga de toda la parte administrativa.",
149:"Coordinación el día del evento",150:"Coordinación logística, técnica y artística para un evento sin contratiempos.",
151:"Un contrato, una factura, un solo interlocutor",152:"Red de artistas locales y regionales",153:"Combinable con nuestros servicios de sonido e iluminación",154:"Eventos públicos y privados, de cualquier aforo",
155:"¿Una programación por imaginar?",156:"próximo espectáculo",157:"Cuéntenos su evento, nosotros nos ocupamos del resto.",
158:"Agenda de conciertos — Alchimie, Cache Candy y nuestros artistas | SLP Sound Light Prod",
159:"Todos los conciertos y próximas fechas de nuestros artistas (Alchimie, Cache Candy, The Fine Allies, NooN Coverband, Panache, Voice of Freedom), en toda Francia.",
160:"Todos nuestros próximos conciertos",161:"Encuentre aquí las próximas fechas de nuestros artistas: conciertos, festivales y veladas abiertas al público.",162:"Cargando la agenda…",
163:"Galería — SLP Sound Light Prod",164:"Fotos de nuestros trabajos: eventos sonorizados, iluminados y organizados por SLP.",165:"Nuestros trabajos",166:"Un vistazo a nuestros servicios de sonido, iluminación y distribución de artistas.",
167:"En vídeo",168:"Nuestros artistas en vídeo",176:"The Fine Allies — Fragmento de concierto",177:"Fragmento de concierto",178:"NooN Coverband — Fragmento de actuación",179:"Fragmento de actuación",
180:"Alchimie — Teaser de versiones Pop Rock",181:"Teaser de versiones Pop Rock",182:"¿Le apetece colaborar?",183:"Presupuesto gratuito y sin compromiso.",
184:"Contacto — Presupuestos de sonido, iluminación y booking | SLP Sound Light Prod",185:"Contacte con SLP para su presupuesto de sonido, iluminación, booking o distribución de artistas, en toda Francia y Europa.",
186:"Hablemos de su proyecto",187:"Sonido, iluminación, booking o artistas: le respondemos rápidamente.",188:"Datos de contacto",189:"Correo electrónico",190:"Teléfono",191:"Dirección",194:"Zona de trabajo",195:"Francia / Europa",
196:"Escríbanos",197:"El formulario abre su programa de correo con el mensaje ya redactado, listo para enviar.",198:"Nombre",199:"Asunto",200:"Presupuesto de servicios técnicos",201:"Otra consulta",202:"Fecha del evento",203:"p. ej. 15 de septiembre de 2026",204:"Mensaje",205:"Enviar el mensaje",206:"También puede escribir directamente a contact@soundlightprod.fr",
207:"Espectáculo de cabaret — Nuestros artistas — SLP Sound Light Prod",208:"Espectáculo de cabaret distribuido por SLP: Panache, revista de cabaret itinerante con plumas, strass y números de vestuario.",209:"← Nuestros artistas",
210:"Revistas de plumas, números de vestuario y puesta en escena deslumbrante, para sus galas y veladas de prestigio.",211:"Revista de cabaret",
212:"Una revista de cabaret itinerante que combina cuadros dinámicos, canto en directo, plumas y strass, para iluminar sus galas, veladas de empresa y eventos privados.",
213:"Galas y veladas de prestigio",214:"Comités de empresa",215:"Eventos privados",216:"Descubrir Panache",
217:"DJ — Nuestros artistas — SLP Sound Light Prod",218:"DJ distribuidos por SLP: sesiones a medida para fiestas privadas, bodas y eventos de empresa.",
219:"Sesiones a medida, del cóctel a la pista de baile, para sus fiestas privadas, bodas y eventos de empresa.",220:"Nuestros DJ llegan muy pronto a esta sección",
221:"Estamos preparando una selección de DJ para sus fiestas privadas, bodas y eventos de empresa. Vuelva pronto o contáctenos ya para hablarlo.",
222:"Grupos de versiones — Nuestros artistas — SLP Sound Light Prod",223:"Grupos de versiones distribuidos por SLP: Alchimie y NooNCoverBand, para animar sus fiestas privadas, bodas y eventos.",
224:"Repertorios de versiones variados, complicidad en el escenario y energía de grupo, para animar fiestas privadas, bodas y eventos festivos.",
225:"Grupo pop/rock formado en 2018. Versiones de los grandes clásicos, impulsadas por la complicidad en el escenario y la alegría de compartir la música.",
226:"Fiestas privadas",227:"Eventos de empresa",228:"Mercados gastronómicos",229:"Descubrir Alchimie",
231:"Dúo de voz y bajo, entre éxitos internacionales, canción francesa y clásicos disco/funk. Cerca de 120 conciertos en campings, bares, mercados locales y fiestas privadas.",
232:"Bodas",233:"Campings",234:"Descubrir NooNCoverBand",
235:"Jazz Soul Funk — Nuestros artistas — SLP Sound Light Prod",236:"Jazz Soul Funk distribuido por SLP: The Fine Allies, siete músicos y una cantante para un espectáculo lleno de groove.",
237:"Groove, metales y voz soul para un ambiente cálido, del cóctel-cena al escenario de concierto.",
239:"La alianza de siete músicos y una cantante para un espectáculo rítmico y cálido, lleno de groove: de James Brown a Jamiroquai.",240:"Veladas de empresa",241:"Descubrir The Fine Allies",
242:"Pop francés — Nuestros artistas — SLP Sound Light Prod",243:"Pop francés distribuido por SLP: Cache Candy, dúo pop-rock electro entre baladas nostálgicas y temas enérgicos.",
244:"Pop-rock electro y energía contagiosa, entre la nostalgia y temas que dan ganas de bailar.",245:"Pop-Rock Electro",
246:"Dúo pop-rock electro nacido en 2008: Bruno-Bastien a la voz y Loïc a la batería, entre baladas nostálgicas y temas enérgicos que unen al público. Más de 300 conciertos por toda Francia, del Printemps de Bourges a Garorock.",
247:"Tributos — Nuestros artistas — SLP Sound Light Prod",248:"Espectáculos tributo distribuidos por SLP: homenajes escénicos a las grandes voces, para sus veladas y eventos.",
249:"Homenajes escénicos a las grandes voces, interpretados por artistas apasionados, para veladas en las que la emoción toma el mando.",
250:"Cuarteto en directo en homenaje a Calogero, para revivir \"En apesanteur\", \"Voler de nuit\" o \"Yalla\" en un concierto de 2 horas.",
251:"Grupo en directo",252:"Cuarteto",253:"Descubrir Tribute Calogero",84:"Tributos",
255:"Alchimie, grupo pop/rock formado en 2018, distribuido por SLP para sus eventos en toda Francia y Europa.",256:"← Grupos de versiones",
257:"Grupo pop/rock impulsado por la complicidad en el escenario y la alegría de compartir la música.",258:"Noticias",259:"Novedades",
260:"Alchimie es un grupo de pop/rock formado en 2018 por antiguos miembros del grupo Antidote.",
261:"El grupo ofrece una selección de versiones pop rock, cantadas en francés, inglés y español, así como algunas composiciones propias, para animar fiestas privadas, bodas, seminarios, conciertos y eventos de empresa.",
262:"Alchimie actúa con su propio equipo de sonido, en formatos que se adaptan tanto a bares como a grandes salas.",
263:"Formación",264:"En el escenario",266:"Voz, guitarra",268:"Guitarra solista",270:"Bajo",272:"Batería",273:"Formación indicativa, puede variar según las fechas.",
274:"Alchimie en concierto, actuación acústica",275:"Alchimie en concierto, grupo completo en el escenario",276:"Alchimie en concierto al aire libre",277:"Vea al grupo en acción",279:"Formado en 2018",
280:"Disponible en toda Francia",281:"Versiones multilingües + temas propios",282:"Encuentre al grupo",283:"En la web",284:"Web oficial ↗",
286:"¿Quiere programarlos?",287:"Reserve a Alchimie",288:"para su evento",289:"SLP distribuye a este artista y coordina toda la logística de su evento.",
291:"Cache Candy, dúo pop-rock electro distribuido por SLP para sus eventos.",292:"← Pop francés",
293:"Un dúo nacido en 2008, entre baladas nostálgicas y energía electro-pop: más de 300 conciertos por toda Francia.",
294:"Cache Candy es un dúo pop-rock electro formado en 2008. Descubierto por una discográfica y una distribuidora, el proyecto ha publicado varios EP y un álbum, y ha dado más de 300 conciertos en Francia.",
295:"El grupo ha creado un universo \"Electro Pop Love\", entre baladas nostálgicas y temas enérgicos que unen al público, íntegramente escritos, compuestos y producidos por ellos mismos con un exigente enfoque DIY. Su trayectoria lo ha llevado hasta las playas del Mediterráneo, ante más de 20 000 personas.",
296:"En 2017, Cache Candy fue elegido \"mejor grupo del Gran Suroeste\" y quedó segundo en un concurso organizado por NRJ12 entre más de 800 candidatos.",
297:"Hoy con Bruno-Bastien y Loïc al frente, el grupo continúa la aventura en formato dúo, en el que la voz, la batería y los instrumentos se intercambian a lo largo del directo, y prepara su nuevo álbum,",
299:"Cache Candy — identidad visual del álbum HAPPY END",300:"Un dúo en el escenario",302:"Voz",304:"5,9K seguidores en Facebook",305:"1,6K seguidores en Instagram",306:"Entre 30 y 40 directos al año",
307:"Donde han tocado",308:"Algunos escenarios del grupo",314:"En imágenes",315:"Cache Candy en concierto",316:"Cache Candy en concierto, público",317:"Cache Candy en concierto acústico",318:"Escuchar",319:"Cache Candy en Spotify",
321:"📄 Dossier de prensa (PDF, en francés) ↓",322:"Formado en 2008",323:"Más de 300 conciertos en Francia",324:"Reserve a Cache Candy",
326:"Grupo tributo en directo a Calogero, distribuido por SLP para sus festivales, fiestas de empresa y conciertos.",327:"← Tributos",
328:"El tributo a Calogero: un cuarteto en directo que revisita los grandes temas de su repertorio, para una velada de complicidad y nostalgia.",
329:"Estrella roja, golpeador de espejo, mástil al revés... Este instrumento le suena a cualquier fan de Calogero. Nicolas, uno de sus fieles admiradores, se propuso personalizarlo él mismo: en 2024 nace este tributo, fruto de un flechazo en un concierto de 2007, la noche que decidió a Nicolas a hacer de la música su profesión.",
330:"Acompañado de tres músicos con talento, el grupo revisita los grandes clásicos del repertorio de Calogero inspirándose en el formato de cuarteto de las giras \"Les Feux d'Artifice Tour\" (2014) y \"Liberté Chérie Tour\" (2018). Artista imprescindible de la canción francesa, sus temas acompañan a un público muy amplio: \"Yalla\", \"Je joue de la musique\", \"En apesanteur\", \"Voler de nuit\", \"C'est dit\"...",
331:"No importa de dónde venga ni su edad: súbase a bordo de 2 horas de concierto con Tribute Calogero y deje que la magia haga el resto.",
332:"El concierto dura 2 horas, íntegramente en directo, con sonido, iluminación y escenografía a cargo de SLP según la fórmula elegida. ¡Una velada de nostalgia y buen humor para pequeños y mayores!",
333:"La formación",334:"El cuarteto",336:"Bajo — fundador",
337:"Marcado por un concierto de Calogero en el Zénith de Toulouse en 2007, lo convirtió en su vocación. Profesional desde hace 12 años, cantautor, publicó un álbum en 2018.",
339:"Guitarra",340:"Enamorado de la música en directo (más de 200 conciertos vistos), apasionado de la guitarra y del sonido analógico. Músico profesional desde hace 25 años.",
342:"Teclados",343:"Formado al piano desde los 15 años, nutrido de rock progresivo y jazz, al servicio del sonido y del estilo con creatividad.",
345:"Titulado por la Musique Académie Internationale de Nancy (2009), con una forma de tocar precisa y eficaz al servicio del tributo.",
347:"Ver",348:"Los teasers",351:"Cuarteto en directo — bajo, guitarra, teclados, batería",352:"2 horas de concierto en directo",353:"Formato de cuarteto inspirado en las giras de Calogero (2014, 2018)",354:"Músicos profesionales, décadas de experiencia en el escenario",
355:"Homenaje a Calogero",356:"Grupo en directo — cuarteto",357:"Ideal para festivales, conciertos y fiestas de empresa",358:"Reserve",
359:"DJ Provisoire — SLP Sound Light Prod",360:"DJ Provisoire, sesiones a medida distribuidas por SLP para sus eventos.",361:"Sonido e iluminación",364:"★ Solo en SLP",365:"Logotipo próximamente",
366:"DJ Provisoire propone sesiones pensadas para acompañar toda la velada: ambiente de cóctel suave y luego una subida progresiva de energía hasta la pista de baile.",
367:"Un repertorio pop, house y disco-funk, adaptable a cualquier ambiente, desde un vino de honor íntimo hasta una fiesta totalmente bailable.",
368:"Un DJ, una velada a medida",369:"DJ en sesión, ambiente club",370:"Vídeos",371:"Algunos fragmentos",372:"Vídeo próximamente",373:"DJ solista",374:"Disponible en toda Francia",376:"Sesiones modulables, del cóctel a la pista de baile",377:"¿Quiere programarlo?",378:"Reserve a DJ Provisoire",
379:"SLP · Sound Light Prod · 173 rue de Courcelles, 75017 Paris · SIRET 130 415 045 00017 — © 2026 ·",
381:"NooNCoverBand, dúo pop/rock/funk disponible en toda Francia, distribuido por SLP para sus eventos.",383:"Un dúo disponible en toda Francia, para veladas tan íntimas como bailables.",
385:"NooNCoverBand nació hace tres años del encuentro de dos artistas: una cantante y un bajista. Con trayectorias musicales variadas (soul, reggae, afro y funk), unieron sus universos para ofrecer veladas memorables a su público.",
386:"Su repertorio, pensado para adaptarse a cualquier ambiente, puede ser tan íntimo (vino de honor, recepción) como totalmente bailable. Cada actuación, de hasta dos horas y media sin pausa, empieza suave antes de ir subiendo de energía a lo largo de la noche.",
387:"En lo musical: mucho pop internacional (Rihanna, Dua Lipa, The Weeknd, Justin Timberlake, Daft Punk), canción francesa (Rita Mitsouko, Niagara, Superbus, Juliette Armanet, -M-) y clásicos disco/funk de los 80 (Chic, Patrick Hernandez, Kool & The Gang, Michael Jackson, Jamiroquai, Claudio Capéo). Un repertorio vivo, que se enriquece regularmente con nuevos temas.",
388:"Tras cerca de ciento veinte conciertos en campings, bares, mercados locales y fiestas privadas, NooNCoverBand se ha ganado un público fiel y numerosos socios que les renuevan regularmente su confianza.",
389:"Un dúo, dos voces complementarias",390:"NooNCoverBand, retrato de la cantante y el bajista",391:"NooNCoverBand, el bajista en concierto",392:"NooNCoverBand, la cantante en plena actuación",393:"NooNCoverBand en concierto, blanco y negro",
394:"Algunos fragmentos en directo",395:"NooNCoverBand — Fragmento en directo",396:"Donde han actuado",397:"Cerca de 120 conciertos a sus espaldas",398:"Bares",399:"Mercados locales",400:"Dúo voz / bajo",402:"Sesiones de hasta 2h30 sin pausa, ambiente modulable",404:"Reserve a NooNCoverBand",
406:"Panache, revista de cabaret itinerante distribuida por SLP: plumas, strass y french cancan para sus galas, veladas de empresa y eventos privados.",407:"← Espectáculo de cabaret",408:"Casinos y campings",409:"Panache — Revista de plumas",
410:"Panache es una revista de cabaret de alta gama, pensada para desplazarse por toda Francia. En un formato modulable de 4 a 8 artistas, encadena cuadros dinámicos, coloridos e innovadores, sostenidos por canto en directo.",
411:"Plumas, strass y french cancan componen el universo visual del espectáculo, en el más puro espíritu de las revistas parisinas de music-hall, hasta un final tricolor que enciende la sala.",
412:"Distribuida por SLP, la revista se adapta a la duración y al formato de su evento, desde un showcase de 30 minutos hasta una gran velada de 1h30, y viaja con su propio equipo técnico de sonido e iluminación.",
413:"El espectáculo",414:"Lo que incluye la revista",415:"De 4 a 8 artistas",416:"Formato modulable según su evento",417:"De 30 min a 1h30",418:"Duración adaptable",419:"Canto en directo",420:"Cuadros dinámicos y coloridos",
421:"Plumas y strass",422:"French cancan, espíritu de revista parisina",423:"Final tricolor",424:"Azul, blanco y rojo",425:"Técnica incluida",426:"Equipo de sonido e iluminación propio",427:"Panache — artista con traje de escena",428:"La revista de gira",
429:"Su navegador no puede reproducir este vídeo.",430:"Ideal para",431:"Una revista que se adapta a su evento",432:"Afterworks y comités de empresa",433:"Casinos",434:"Campings y residencias vacacionales",435:"Revista itinerante",436:"Equipo de sonido e iluminación incluido",
437:"¿Quiere programar Panache?",438:"Reserve esta revista",439:"SLP distribuye este espectáculo y coordina toda la logística de su evento.",
441:"The Best ABBA Tribute, grupo tributo en directo a ABBA, distribuido por SLP para sus festivales, fiestas de empresa y conciertos.",442:"Tributo a ABBA",
443:"Un grupo completo en directo que hace revivir los grandes éxitos de ABBA: dos cantantes excepcionales y músicos experimentados, para una velada de nostalgia y buen humor.",444:"2 cantantes + músicos",
445:"En la historia del pop, ABBA ocupa un lugar aparte. ¿Quién no recuerda éxitos atemporales como \"Dancing Queen\", \"Waterloo\", \"Mamma Mia\", \"Voulez-Vous\" o \"The Winner Takes It All\"? Con más de 200 millones de álbumes vendidos (370 millones de discos en total), ABBA sigue siendo uno de los grupos más vendidos de la historia de la música.",
446:"The Best ABBA Tribute está liderado por dos cantantes solistas en plena forma y músicos que tocan íntegramente en directo, una exigencia poco común en el mundo de los tributos y una de las claves de su éxito. El grupo ha actuado ante más de 15 000 espectadores en Helmond (Kasteeltuinconcerten) y en el festival TT Assen, así como en el extranjero: Rusia, Rumanía, Liechtenstein.",
447:"Aclamado por la prensa neerlandesa e internacional como uno de los mejores homenajes a ABBA del mundo, el grupo promete una velada de nostalgia y buen humor, para pequeños y mayores, con éxitos atemporales como \"Dancing Queen\", \"Waterloo\", \"Mamma Mia\", \"Voulez-Vous\" o \"The Winner Takes It All\".",
448:"El teaser",449:"Grupo completo en directo — voces, músicos, técnico de sonido",450:"Más de 15 000 espectadores en Helmond y TT Assen",451:"Reconocido por la prensa neerlandesa e internacional",452:"Homenaje a ABBA",453:"Grupo en directo — 2 cantantes + músicos",
455:"The Fine Allies, grupo de funk, soul y rhythm'n'blues distribuido por SLP para sus eventos en toda Francia y Europa.",456:"← Jazz Soul Funk",457:"Siete músicos y una cantante unidos por un mismo lema: el groove.",
458:"The Fine Allies es la alianza de siete músicos y una cantante de horizontes musicales diversos, unidos por las mismas ganas: tocar la música que les hace vibrar.",
459:"En el escenario, el grupo ofrece un espectáculo rítmico y cálido entre funk, soul y rhythm'n'blues, con toques de jazz, reggae y rock: de James Brown a Jamiroquai, pasando por Stevie Wonder, Amy Winehouse o Tower of Power.",
460:"El grupo actúa con regularidad en toda Francia: festivales, bares, bodas y eventos privados.",461:"Ocho artistas en el escenario",465:"Teclados, coros",467:"Saxofón tenor",469:"Saxofón alto",471:"Trompeta",474:"Batería, coros",
475:"The Fine Allies en concierto, sección de metales",476:"The Fine Allies en concierto, grupo completo en el escenario",477:"The Fine Allies en concierto al aire libre",478:"The Fine Allies en concierto, solo de trombón",486:"8 músicos",487:"Festivales, bodas y eventos privados",488:"Reserve a The Fine Allies",
490:"Voice of Freedom, espectáculos tributo a Etta James y Nina Simone, distribuidos por SLP para sus eventos.",
493:"Un vibrante homenaje a las grandes voces del soul y del blues estadounidenses, entre Etta James y Nina Simone.",
496:"Voice of Freedom es un grupo de cinco músicos apasionados por el blues y el soul, reunidos en torno a la cantante Wiennen Silveira. Tras el éxito de su Tributo a Nina Simone en 2018, volvieron a unirse para rendir homenaje a otra figura icónica: Etta James.",
497:"Etta James fue una artista habitada por la rabia: contra una infancia desdichada, contra la América paternalista, contra los hombres que la traicionaron; una rabia que la llevó a sobrevivir a las drogas y a la angustia para, contra viento y marea, seguir viviendo y cantando. Rendir homenaje a esta inmensa cantante, poco conocida en Francia, y expresar la belleza de su grito: ese es el ambicioso proyecto que se han propuesto los músicos de Voice of Freedom.",
498:"Durante un espectáculo, se sumergen en la América negra de los años 1950-60 y siguen el caótico recorrido de una diva virtuosa y atormentada, que redefinió el canto blues e inspiró a las grandes voces del otro lado del Atlántico. Más que una imitación, su Tributo es una verdadera interpretación de la obra de Etta James: Wiennen Silveira, acompañada de cuatro músicos con talento, lleva al público tras sus pasos, a través de sus desengaños amorosos, sus alegrías sin límites y su rabia.",
499:"El grupo ofrece también un segundo espectáculo tributo, dedicado a",
501:", creado en 2018. Ambos espectáculos han sido aplaudidos en el escenario y en la radio, en particular en France Bleu / ICI, donde el grupo fue invitado al programa « La Nouvelle Scène ».",
502:"La trayectoria de Wiennen Silveira resuena especialmente con la de Nina Simone. Nacida en la India, creció en Catar en el seno de una familia de trabajadores extranjeros, en un contexto de fuerte discriminación. Allí aprendió piano y entró en el coro de su parroquia. Más tarde, sus estudios la llevaron a descubrir el blues, el jazz y el rock estadounidenses, con Nina Simone y Etta James a la cabeza, dos influencias que la marcarían para siempre. Para huir de un matrimonio concertado, se marchó sola a Hyderabad, donde empezó a cantar y a tocar la guitarra en los bares de la ciudad. Después se instaló en el sur de Francia, donde fundó en 2012 el trío funk-rock WAT, antes de lanzar en 2018, con los músicos de Voice of Freedom, el proyecto dedicado a Nina Simone.",
503:"Cinco artistas en el escenario",507:"Piano",510:"Dos espectáculos",511:"Etta James y Nina Simone",512:"Diva del blues, años 50-60",513:"Creado en 2018",514:"Voice of Freedom en el escenario",515:"Han hablado de ellos",516:"Un grupo que ha pasado por las ondas",
519:"5 músicos",520:"Con sede en Châteauroux, Indre",522:"2 espectáculos: Etta James, Nina Simone",523:"Reserve a Voice of Freedom",
524:"Aviso legal — SLP Sound Light Prod",525:"← Volver al sitio",526:"Editor del sitio",528:"SARL (sociedad limitada) con un capital social de 2 500 €",529:"SIRET: 130 415 045 00017",530:"Código APE: 9001Z",
531:"Domicilio social: 173 rue de Courcelles, 75017 París, Francia",532:"Correo electrónico:",533:"Teléfono: +33 6 31 94 96 53",534:"Alojamiento",535:"Sitio alojado por Cloudflare, Inc.",536:"101 Townsend Street, San Francisco, CA 94107, Estados Unidos",
537:"Propiedad intelectual",538:"Todos los contenidos de este sitio (textos, imágenes, logotipos, gráficos) son propiedad de SLP o de sus socios, salvo indicación contraria, y no pueden reproducirse sin autorización previa.",
539:"Datos personales",540:"La información recogida a través de los formularios de este sitio (contacto, pedido, reserva) se utiliza exclusivamente para tramitar su solicitud y nunca se cede a terceros con fines comerciales. De acuerdo con el RGPD, usted tiene derecho a acceder, rectificar y suprimir sus datos, que puede ejercer por correo electrónico a",
541:"Cookies",542:"Este sitio no utiliza cookies de seguimiento publicitario. Pueden utilizarse cookies técnicas para el correcto funcionamiento del carrito de compra.",
170:"Prendre Racine",
}
JS = {"`Nom : ${name}\\nEmail : ${email}\\nDate de l'événement : ${dateEvent}":"`Nombre: ${name}\\nCorreo: ${email}\\nFecha del evento: ${dateEvent}",
      "Aucun concert público":"",
      "Aucun concert public programmé pour le moment — revenez bientôt !":"No hay conciertos públicos programados por el momento. ¡Vuelva pronto!",
      "Agenda momentanément indisponible.":"Agenda no disponible temporalmente."}
LOCALE="es-ES"
T.update({544:"Grupo completo en directo, homenaje a los grandes éxitos de ABBA.",546:"Logotipo de The Best ABBA Tribute",547:"Grupo completo en directo, aclamado por la prensa neerlandesa e internacional, para revivir los grandes éxitos de ABBA con dos cantantes excepcionales y músicos experimentados.",548:"Fiestas de empresa",549:"Descubrir The Best ABBA Tribute",442:"Tributo a ABBA"})
